version: '2'

services:

  app:
    image: ecomrcapp
    depends_on:
    - mongo
    volumes:
    - ./app:/var/app
    - ./commands:/var/commands
    working_dir: /var/app
    command: sh ../commands/rundev.sh
    ports: 
    - "8080:80"
    expose:
    - "80"
    networks:
    - ecomrc
    env_file:
    - .env.local

  mongo:
    image: mongo:latest
    volumes:
    - ./mongodb:/data/db
    ports: 
    - "27018:27017"
    expose:
    - "27017"
    networks:
    - ecomrc
    env_file:
    - .env.local

networks:
  ecomrc:
    driver: bridge
